Web/Controllers/AppointmentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DataAccess;
using Common;
using Web.Helpers;

namespace Web.Controllers
{
    [Authorize]
    public class AppointmentsController : ControllerBase
    {
        private IScopeFactory scopeFactory;

        public AppointmentsController(IScopeFactory scopeFactory)
        {
            this.scopeFactory = scopeFactory;
        }

        [HttpPost]
        public ActionResult Create(ViewModels.Appointments.Create model)
        {
            var entity = new Model.Appointment
            {
                Task = new Model.Task
                {
                    Id = model.TaskId
                },

                StartDate = model.Date.AddHours(model.StartHour),
                EndDate = model.Date.AddHours(model.EndHour).AddMinutes(59).AddSeconds(59)
            };

            scopeFactory.Do(x => x.Execute(new Logic.Appointment.CreateAppointment(entity)));
            return Json(new
            {
                id = entity.Id
            });
        }

        [HttpPost]
        public ActionResult Update(ViewModels.Appointments.Update model)
        {
            using(var scope = scopeFactory.Get())
            {
                var entity = scope.Query(new Logic.Appointment.GetAppointmentById(model.Id));
                entity.StartDate = model.NewDate.AddHours(model.NewStartHour);
                entity.EndDate = model.NewDate.AddHours(model.NewEndHour).AddMinutes(59).AddSeconds(59);

                scope.Execute(new Logic.Appointment.UpdateAppointment(entity));

                scope.Commit();
            }

            return View();
        }

        public ActionResult GetForWeek(string id)
        {
            DateTime startDay = DateTime.Parse(id);
            var appointments = scopeFactory.Do(x => x.Query(new Logic.Appointment.GetAppointmentsForUserAndWeek(User.Id, startDay)));

            return Json(appointments.Select(x => new ViewModels.Appointments.Appointment
            {
                id = x.Id,
                name = x.Task.Name,
                taskId = x.Task.Id,
                startDate = x.StartDate.ToString("yyyy-MM-dd"),
                startHour = x.StartDate.Hour,
                endDate = x.EndDate.ToString("yyyy-MM-dd"),
                endHour = x.EndDate.Hour,
                progress = x.Progress,
                duration = x.EndDate.Hour - x.StartDate.Hour + 1
            }), JsonRequestBehavior.AllowGet);
        }

        public ActionResult Remove(int id)
        {
            scopeFactory.Do(x => x.Execute(new Logic.Appointment.DeleteAppointment(id)));

            return Json("OK", JsonRequestBehavior.AllowGet);
        }

        public ActionResult Edit(int id)
        {
            var entity = scopeFactory.Do(x => x.Query(new Logic.Appointment.GetAppointmentById(id)));
            ViewData.Model = new ViewModels.Appointments.Edit
            {
                AvailableDates = CalendarHelper.GetWeekDays(entity.StartDate.Date).AsNamed(x => string.Format("{0:yyyy-MM-dd} ({1})", x, x.DayOfWeek)),
                AvailableHours = Enumerable.Range(7, 12).ToArray(),

                Id = entity.Id,
                Date = entity.StartDate.Date,
                StartHour = entity.StartDate.Hour,
                EndHour = entity.EndDate.Hour + 1
            };

            return PartialView();
        }

        [HttpPost]
        public ActionResult Edit(ViewModels.Appointments.Edit model)
        {
            if(model.EndHour <= model.StartHour)
            {
                ModelState.AddModelError("EndHour", "Cannot finish before start");
            }

            var startDate = model.Date.AddHours(model.StartHour);
            var endDate = model.Date.AddHours(model.EndHour).AddSeconds(-1);

            if(scopeFactory.Do(x => x.Query(new Logic.Appointment.IsAnyOverlapping(startDate, endDate, model.Id, User.Id))))
            {
                ModelState.AddModelError("StartHour", "Appointment overlaps with another");
                ModelState.AddModelError("EndHour", "Appointment overlaps with another");
            }

            if(ModelState.IsValid)
            {
                using(var scope = scopeFactory.Get())
                {
                    var entity = scope.Query(new Logic.Appointment.GetAppointmentById(model.Id));

                    entity.StartDate = model.Date.AddHours(model.StartHour);
                    entity.EndDate = model.Date.AddHours(model.EndHour).AddSeconds(-1);

                    scope.Execute(new Logic.Appointment.UpdateAppointment(entity));

                    scope.Commit();

                    return Json(new ViewModels.Appointments.Appointment
                    {
                        id = entity.Id,
                        name = entity.Task.Name,
                        taskId = entity.Task.Id,
                        startDate = entity.StartDate.ToString("yyyy-MM-dd"),
                        startHour = entity.StartDate.Hour,
                        endDate = entity.EndDate.ToString("yyyy-MM-dd"),
                        endHour = entity.EndDate.Hour,
                        progress = entity.Progress,
                        duration = entity.EndDate.Hour - entity.StartDate.Hour + 1
                    });
                }
            }
            else
            {
                model.AvailableDates = CalendarHelper.GetWeekDays(model.Date.Date).AsNamed(x => string.Format("{0:yyyy-MM-dd} ({1})", x, x.DayOfWeek));
                model.AvailableHours = Enumerable.Range(7, 12).ToArray();

                ViewData.Model = model;

                Response.StatusCode = 550;
                return PartialView();
            }
        }

        public ActionResult UpcomingAppointments()
        {
            var now = DateTime.Now.TranslateToTimeZone(User.TimeZone);
            var data = scopeFactory.Do(x => x.Query(new Logic.Appointment.GetAppointmentsForUserAndDay(User.Id, now)));
            ViewData.Model = new ViewModels.Appointments.UpcomingAppointments(data, now);
            return View();
        }
    }
}

Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
    <title>@ViewBag.Title</title>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <link rel="stylesheet" href="@Url.Content("~/Content/layout.css")" type="text/css" />    
    <link rel="stylesheet" href="@Url.Content("~/Content/openid.css")" type="text/css"/>
    <link rel="stylesheet" href="@Url.Content("~/Content/openid-shadow.css")" type="text/css"/>
    <link rel="stylesheet" href="@Url.Content("~/Content/jquery-ui.css")" type="text/css"/>
    <link rel="stylesheet" href="@Url.Content("~/Content/jquery.contextMenu.css")" type="text/css"/>
    <link rel="stylesheet" href="@Url.Content("~/Content/style.css")" type="text/css" />

    <script type="text/javascript">var rootPath = '@Url.Content("~/")';</script>

    <script type="text/javascript" src="@Url.Content("~/Scripts/jquery-1.7.1.min.js")"></script>    
    <script type="text/javascript" src="@Url.Content("~/Scripts/jquery.contextMenu.js")"></script>  
    <script type="text/javascript" src="@Url.Content("~/Scripts/jquery-ui-1.8.18.min.js")"></script>        
    <script type="text/javascript" src="@Url.Content("~/Scripts/jquery.validate.min.js")"></script> 
    <script type="text/javascript" src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.js")"></script> 
    <script type="text/javascript" src="@Url.Content("~/Scripts/jquery.unobtrusive-ajax.min.js")"></script>  
    <script type="text/javascript" src="@Url.Content("~/Scripts/misc.js")"></script>  

    <script type="text/javascript">

        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-30901680-1']);
        _gaq.push(['_trackPageview']);

        (function () {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();

</script>
</head>
<body>
    <div id="log-on">
        @Html.Partial("_LogOnPartial")
    </div>
    <div id="header">
    <div id="top_text">
        <h1>
            <a href="@Url.RouteUrl("Start")">Mr. Bean's Planner</a></h1>
        <h3>
            Plan your future!</h3>
    </div>
        <nav>
            @Html.Partial("_Menu")
        </nav>
    </div>
    <div id="container">
        <div id="content">
            @RenderBody()
        </div>       
    </div>
    <footer>
        <div id="footer">
            <!-- If you wish to delete this line of code please purchase our commercial license http://www.sixshootermedia.com/shop/commercial-license/ -->
            <p>
                <!-- you can delete below here -->
                Created during Hackfest #3 by Mr Bean's Private Army team.<br />
                Template design by <a href="http://www.sixshootermedia.com">Six Shooter Media</a>.
            </p>
        </div>
    </footer>

    <div id="loading" class="ui-widget-overlay" style="width:100%; height: 100%;display:none">
        <div id="loading-box">
            <img src="@Url.Content("~/Content/images/ajax-loader.gif")" />
        </div>
    </div>
</body>
</html>

Web/Views/Shared/_LogOnPartial.cshtml
@if(Request.IsAuthenticated)
{
    <text>Welcome <strong>@User.Identity.Name</strong>! [ @Html.ActionLink("Log Off", "LogOff", "Account") ]</text>
}
else
{
    @:[ @Html.ActionLink("Log On", "LogOn", "Account") ]
}

Web/Views/Shared/_Menu.cshtml
<ul id="nav">
    <li>@Html.RouteLink("Home", "Start")</li>
    <li>@Html.RouteLink("Getting started", "Guide")</li>
    
    @if (User.Identity.IsAuthenticated)
    {
        <li><a href="@Url.Action("Manage", "Account")">My profile</a></li>
        <li>@Html.RouteLink("Calendar", "CalendarViewToday")</li>
        <li><a href="@Url.Action("UpcomingAppointments", "Appointments")">Upcoming appointments</a></li>
    }
    
    <!--<li><a href="#" class="active">Active Link</a></li>-->
</ul>